### ISSUE TITLE
Browser version is "node"

### ISSUE THREAD

**Issue by lukepighetti** [DamonOehlman/detect-browser#125] opened 2019-11-30 16:25 UTC
Working on a Nuxt project and `detect-browser` keeps saying `browser.name` is `node`

**Comment by DamonOehlman** [comment] 2019-12-01 01:28
@lukepighetti I haven't worked with Nuxt yet (but it looks interesting).  This sounds like a code path for detection might be getting walked during server side rendering and then serialised into client-side state.

If your project source is on github I'm more than happy to take a look.

**Comment by lukepighetti** [comment] 2019-12-01 14:41
I believe you're correct, it does seem to be a case of it being server-side rendered and then the result baked into the project. Unfortunately I don't have a reproduction for you, I'm fine with you closing this issue. Up to you.

**Comment by DamonOehlman** [comment] 2019-12-01 23:00
@lukepighetti Thanks for getting back to me.  I think if it is due to server side rendering then closing the issue is probably the most appropriate thing, so I'll do that now.

Thanks for raising the issue as it should give others who hit the same issue in the future a hint about what is going on.

**Closed by DamonOehlman** 2019-12-01 23:00 UTC
